
from PyQt5 import QtCore, QtGui, QtWidgets
import menubar1
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTheme = QtWidgets.QMenu(self.menuView)
        self.menuTheme.setObjectName("menuTheme")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.newLB = QtWidgets.QAction(MainWindow)
        self.newLB.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.newLB.setFont(font)
        self.newLB.setObjectName("newLB")
        self.openLB = QtWidgets.QAction(MainWindow)
        self.openLB.setObjectName("openLB")
        self.saveLB = QtWidgets.QAction(MainWindow)
        self.saveLB.setObjectName("saveLB")
        self.save_asLB = QtWidgets.QAction(MainWindow)
        self.save_asLB.setObjectName("save_asLB")
        self.copyLB = QtWidgets.QAction(MainWindow)
        self.copyLB.setObjectName("copyLB")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.darkLB = QtWidgets.QAction(MainWindow)
        self.darkLB.setCheckable(True)
        self.darkLB.setObjectName("darkLB")
        self.lightLb = QtWidgets.QAction(MainWindow)
        self.lightLb.setCheckable(True)
        self.lightLb.setObjectName("lightLb")
        self.defaultLB = QtWidgets.QAction(MainWindow)
        self.defaultLB.setCheckable(True)
        self.defaultLB.setObjectName("defaultLB")
        self.tool1LB = QtWidgets.QAction(MainWindow)
        self.tool1LB.setObjectName("tool1LB")
        self.tool2LB = QtWidgets.QAction(MainWindow)
        self.tool2LB.setObjectName("tool2LB")
        self.tool3LB = QtWidgets.QAction(MainWindow)
        self.tool3LB.setObjectName("tool3LB")
        self.menuFile.addAction(self.newLB)
        self.menuFile.addAction(self.openLB)
        self.menuFile.addAction(self.saveLB)
        self.menuFile.addAction(self.save_asLB)
        self.menuEdit.addAction(self.copyLB)
        self.menuEdit.addAction(self.actionPaste)
        self.menuTheme.addAction(self.darkLB)
        self.menuTheme.addAction(self.lightLb)
        self.menuTheme.addAction(self.defaultLB)
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menuTools.addAction(self.tool1LB)
        self.menuTools.addAction(self.tool2LB)
        self.menuTools.addAction(self.tool3LB)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.outputLB = QtWidgets.QLabel(self.centralwidget)
        self.outputLB.setEnabled(True)
        self.outputLB.setGeometry(QtCore.QRect(250, 150, 320, 100))
        self.outputLB.setToolTip("")
        self.outputLB.setStatusTip("")
        self.outputLB.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "font: 16pt \"Arial\";")
        self.outputLB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputLB.setLineWidth(12)
        self.outputLB.setObjectName("outputLB")

        self.newLB.triggered.connect(lambda: self.msg("New"))
        self.openLB.triggered.connect(lambda: self.msg("Open"))
        self.saveLB.triggered.connect(lambda: self.msg("Save"))
        self.save_asLB.triggered.connect(lambda: self.msg("Save as"))
        self.copyLB.triggered.connect(lambda: self.msg("Copy"))
        self.actionPaste.triggered.connect(lambda: self.msg("Paste"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def msg(self, result):
        
        self.open("menubar1")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.newLB.setText(_translate("MainWindow", "New"))
        self.newLB.setToolTip(_translate("MainWindow", "New"))
        self.newLB.setWhatsThis(_translate("MainWindow", "Cteart a file"))
        self.newLB.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.openLB.setText(_translate("MainWindow", "Open"))
        self.openLB.setWhatsThis(_translate("MainWindow", "Open a file"))
        self.openLB.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.saveLB.setText(_translate("MainWindow", "Save"))
        self.saveLB.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.save_asLB.setText(_translate("MainWindow", "Save as"))
        self.save_asLB.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.copyLB.setText(_translate("MainWindow", "Copy"))
        self.copyLB.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.darkLB.setText(_translate("MainWindow", "Dark"))
        self.lightLb.setText(_translate("MainWindow", "Light"))
        self.defaultLB.setText(_translate("MainWindow", "Default"))
        self.tool1LB.setText(_translate("MainWindow", "tool1LB"))
        self.tool2LB.setText(_translate("MainWindow", "Tool 2"))
        self.tool3LB.setText(_translate("MainWindow", "Tool 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
